// OutOfProcessCOMServer.idl : IDL source for OutOfProcessCOMServer
//

// This file will be processed by the MIDL tool to
// produce the type library (OutOfProcessCOMServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(f18d5855-7d92-4aed-ada7-87d1a9595377),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMouse : IDispatch
{
	[id(2)] HRESULT click(BSTR buttonName);
	[id(3)] HRESULT scroll(LONG amount);
};

[
	uuid(5790d466-f696-470f-a9f0-707d483e5d13),
	nonextensible,
]
interface IKeyboard : IUnknown {
	HRESULT pressKey(LPCWSTR keyName);
	HRESULT releaseKey(LPCWSTR keyName);
};

[
	uuid(06ee9bc1-85fc-409a-a0bc-ae9f8a1037eb),
	version(1.0),
]
library OutOfProcessCOMServerLib
{
	importlib("stdole2.tlb");
	[
		uuid(3eb17078-42bb-425f-adaa-e050e6b3add4)
	]
	coclass Mouse
	{
		[default] interface IMouse;
		interface IKeyboard;
	};
};

import "shobjidl.idl";
